version: '2'
services:
    mongo:
        image: mongo:latest
        volumes:
          - ./data/db:/data/db
        ports:
            - "27017:27017"
        expose:
            - "27017"  
    web:
        build: .
        ports:
          - "3000:3000"
        expose: 
          - "3000"
        depends_on:
          - mongo
        links:
          - mongo