version: '2'
services:
    mongo:
        image: mongo:latest
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        expose:
            - 27017  
    web:
        build: .
        ports:
          - 4200:4200
        expose: 
          - 4200
        depends_on:
          - mongo
        links:
          - mongo
